theme: minima

title: Chad's Blog
author: Chad Baldwin
email: blog@chadbaldwin.net
url: https://chadbaldwin.net

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

description: >
  My first blog. Probably no one else will ever read it, but oh well.

# Minima variables
twitter_username:  chad_baldwin
github_username:   chadbaldwin
linkedin_username: chadbaldwin
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
rss: rss

show_excerpts: false

# Used by simple links page
social-links:
  Resume:          /resume
  LinkedIn:        https://linkedin.com/in/chadbaldwin
  StackOverflow:   https://stackoverflow.com/users/3474677
  HackerRank:      https://hackerrank.com/chadwin
  GitHub:          https://github.com/chadbaldwin
  Microsoft Learn: https://learn.microsoft.com/en-us/users/chadbaldwin/transcript/v0ylxf6nq5l8ny8
  Twitter:         https://twitter.com/chad_baldwin
  Reddit:          https://reddit.com/user/chadbaldwin
  Credly:          https://credly.com/users/chadbaldwin
  PluralSight:     https://app.pluralsight.com/profile/chadbaldwin
  Website:         /

# plugin: jekyll-seo-tag
twitter:
  username: chad_baldwin
  card: summary_large_image
social:
  name: Chad Baldwin
  links:
    - https://twitter.com/chad_baldwin
    - https://linkedin.com/in/chadbaldwin
    - https://github.com/chadbaldwin

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - resume.html
  - archive.html
#  - books.md # Commenting out for now as putting more focus on pluralsight than reading
  - bookmarks.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics:
  - UA-185058308-1 # Old GA Universal Analytics property
  - G-RY6FRPMXHZ # New GA4 property

gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 5

# The github repo that is to be used for looking up comments
comments_repo: chadbaldwin/chadbaldwin.github.io

defaults:
  - scope:
      path: ""
    values:
      image: https://s.gravatar.com/avatar/2136e716a089f4a3794f4007328c7bfb?s=800 # Apply default site image
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true
